version: "3.8"
services:
  mysql: 
    image: flask_db
    build: ./db
    container_name: mysql
  flask-app:
    container_name: flask-app
    image: flask-app
    build: ./flask-app
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    