version: "3.8"
services:
  mysql:
    image: flask-db
    build: ./db
    volumes:
      - mysql-data: /home/azureuser/mysql_datadir
  flask-app:
    image: flask-app
    environment:
      DATABASE_URI: DATABASE_URI
    build: ./flask-app
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    depends_on:
      - mysql

volumes:
  mysql-data: