version: "3.8"
services:
  mysql: 
    image: flask-db
    build: ./db
    container_name: mysql
  flask-app:
    container_name: flask-app
    image: flask-app
    build: ./flask-app
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    depends_on:
      - mysql
    args:
      DATABASE_URI: mysql+pymysql://root:password@mysql:3306/
    