version: "3.8"
services:
  mysql:
    image: flask-db
    build: ./db
    volumes:
      - mysql-data:/var/lib/mysql
  flask-app:
    image: flask-app
    environment:
      DATABASE_URI: "mysql+pymysql://root:password@mysql:3306/flask-db"
    build: ./flask-app
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    depends_on:
      - mysql

volumes:
  mysql-data: