version: "3.8"
services:
  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
    - type: bind
      source: ./nginx.conf
      target: /etc/nginx/nginx.conf
    ports:
    - target: 80
      published: 80
      protocol: tcp
